# Generated by Django 5.2.14 on 2026-05-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClockWidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('pos_left', models.CharField(default='2%', max_length=20)),
                ('pos_top', models.CharField(default='2%', max_length=20)),
                ('font_size', models.CharField(default='1rem', max_length=20)),
                ('color', models.CharField(default='#ffffff', max_length=20)),
                ('z_index', models.PositiveIntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Clock Widget Config',
            },
        ),
        migrations.CreateModel(
            name='IndexImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='core/images/')),
                ('layer', models.CharField(choices=[('background', 'Background (Parallax)'), ('main', 'Main'), ('sticker', 'Sticker')], default='main', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('pos_left', models.CharField(default='50%', max_length=20)),
                ('pos_top', models.CharField(default='50%', max_length=20)),
                ('width', models.CharField(default='160px', max_length=20)),
                ('height', models.CharField(default='auto', max_length=20)),
                ('rotate', models.IntegerField(default=0)),
                ('z_index', models.PositiveIntegerField(default=10)),
            ],
            options={
                'ordering': ['layer', 'order', 'z_index'],
            },
        ),
        migrations.CreateModel(
            name='ParallaxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField(default=0.4)),
                ('blur_px', models.IntegerField(default=0)),
                ('overlay_opacity', models.FloatField(default=0.3)),
            ],
            options={
                'verbose_name': 'Parallax Config',
            },
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('bg_text', 'Background Text'), ('block1', 'Text Block 1'), ('block2', 'Text Block 2'), ('block3', 'Text Block 3')], default='block1', max_length=20)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('pos_left', models.CharField(default='5%', max_length=20)),
                ('pos_top', models.CharField(default='5%', max_length=20)),
                ('font_size', models.CharField(default='1rem', max_length=20)),
                ('color', models.CharField(default='#ffffff', max_length=20)),
                ('z_index', models.PositiveIntegerField(default=20)),
            ],
        ),
    ]
