# Generated by Django 5.2.14 on 2026-05-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('font_family', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('url', 'Web Font URL'), ('upload', 'Uploaded File')], max_length=10)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=400)),
                ('format', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='scenelayer',
            name='layer_type',
            field=models.CharField(choices=[('bg_image', 'Background Image'), ('parallax_far', 'Parallax Far'), ('bg_text', 'Background Text'), ('main_image', 'Main Image'), ('text', 'Text'), ('clock', 'Clock'), ('menu_button', 'Menu Button'), ('user_profile', 'User Profile'), ('sticker', 'Sticker'), ('parallax_near', 'Parallax Near'), ('parallax_ultra_near', 'Parallax Ultra Near')], max_length=40),
        ),
    ]
