# Generated by Django 5.2.14 on 2026-05-16 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customfont_alter_scenelayer_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenelayer',
            name='height',
            field=models.FloatField(default=200, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='scenelayer',
            name='layer_tier',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='scenelayer',
            name='layer_type',
            field=models.CharField(choices=[('bg_image', 'Background Image'), ('parallax_far', 'Parallax Far'), ('bg_text', 'Background Text'), ('main_image', 'Main Image'), ('text', 'Text'), ('clock', 'Clock'), ('menu_button', 'Menu Button'), ('user_profile', 'User Profile'), ('auth_buttons', 'Auth Buttons'), ('sticker', 'Sticker'), ('parallax_near', 'Parallax Near'), ('parallax_ultra_near', 'Parallax Ultra Near')], max_length=40),
        ),
        migrations.AlterField(
            model_name='scenelayer',
            name='opacity',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='scenelayer',
            name='scale',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='scenelayer',
            name='width',
            field=models.FloatField(default=200, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
