# Generated by Django 5.2.14 on 2026-05-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_item_image_url_item_image_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
