# Generated by Django 5.2.14 on 2026-05-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='item',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='purchased_at',
            new_name='acquired_at',
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='memo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
