# Generated by Django 5.2.14 on 2026-05-13 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('credit', '크레딧'), ('inventory', '아이템')], default='credit', max_length=20)),
                ('price_points', models.PositiveIntegerField()),
                ('credit_amount', models.PositiveIntegerField(blank=True, help_text="item_type이 'credit'일 때만 입력", null=True)),
                ('image', models.ImageField(blank=True, help_text='PNG, WebP 권장', null=True, upload_to='shop_items/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('game', '게임'), ('book', '책'), ('hobby', '취미'), ('other', '기타')], default='other', max_length=20)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('spent_at', models.DateField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField()),
                ('credits_gained', models.PositiveIntegerField(default=0)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.shopitem')),
            ],
        ),
    ]
