# Generated by Django 5.2.14 on 2026-05-10 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='image',
            field=models.ImageField(blank=True, help_text='PNG, WebP 권장', null=True, upload_to='shop_items/'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='item_type',
            field=models.CharField(choices=[('credit', '크레딧'), ('inventory', '아이템')], default='credit', max_length=20),
        ),
        migrations.AlterField(
            model_name='creditlog',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='creditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='credits_gained',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='points_spent',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='credit_amount',
            field=models.PositiveIntegerField(blank=True, help_text="item_type이 'credit'일 때만 입력", null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='price_points',
            field=models.PositiveIntegerField(),
        ),
    ]
