# Generated by Django 5.2.14 on 2026-05-17 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_review_image', models.ImageField(blank=True, help_text='후기에 이미지가 없을 때 표시할 기본 이미지', null=True, upload_to='shop_settings/')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='credits_gained',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='price_points',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_reviews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CreditLog',
        ),
    ]
