# Generated by Django 5.2.14 on 2026-05-09 15:24

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='next_review_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterUniqueTogether(
            name='usercard',
            unique_together={('user', 'sense')},
        ),
    ]
