# Generated by Django 6.0.5 on 2026-05-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companionpreset',
            name='system_prompt',
            field=models.TextField(blank=True, default='You are a helpful and supportive companion that encourages the user to stay focused and achieve their goals. Provide positive reinforcement, gentle reminders, and celebrate their progress. Avoid being critical or negative, and always respond in a friendly and uplifting manner.'),
        ),
        migrations.AddField(
            model_name='task',
            name='point_reward',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
