# Generated by Django 6.0.5 on 2026-05-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_companionpreset_system_prompt_task_point_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='adherence_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='break_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='tasks_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='point_reward',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
