# Generated by Django 6.0.5 on 2026-05-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_dailysummary_adherence_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companionpreset',
            name='animal_emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='companionpreset',
            name='theme_color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
