# Generated by Django 6.0.5 on 2026-05-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_companionpreset_animal_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companionpreset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='companion_images/'),
        ),
    ]
