# Generated by Django 6.0.5 on 2026-05-17 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0002_initial_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'status'], name='atelier_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'sort_order'], name='atelier_proj_order_idx'),
        ),
    ]
