# Generated by Django 6.0.5 on 2026-05-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0003_add_project_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
